version: "3.5"

services:
  pxc:
    image: percona/percona-xtradb-cluster:${PXC_VERSION}
    container_name: pxc
    # restart: always
    privileged: true
    volumes:
      - data:/var/lib/mysql
      # - ./mysql/log:/var/log
      - ./mysql/cnf/my.cnf:/etc/my.cnf
    ports:
      # 不采用host模式，选择映射所有端口
      - "3307:3306"
      - "4444:4444"
      - "4567:4567"
      - "4568:4568"
    environment:
      # - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - XTRABACKUP_PASSWORD=${XTRABACKUP_PASSWORD}
      - CLUSTER_JOIN=${CLUSTER_JOIN}

volumes:
  data:
    name: data
